openapi: 3.0.1
info:
  title: TestBasicAuthREST
  description: API Definition of TestBasicAuthREST
  version: 1.0.0
servers:
- url: http://localhost:8290/TestBasicAuthREST
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /post:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
